# Generated by Django 6.0.1 on 2026-01-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('enrollment_date', models.DateField()),
                ('student_class', models.CharField(help_text='e.g. 1, 2, 10, 12-A', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ALUMNI', 'Alumni'), ('TC_ISSUED', 'TC Issued')], default='ACTIVE', max_length=20)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
