# Generated by Django 6.0.1 on 2026-01-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_address_remove_student_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(help_text='Unique Registration/Roll Number', max_length=20, unique=True),
        ),
    ]
