# Generated by Django 6.0.1 on 2026-01-22 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_alter_feehead_due_months_alter_feehead_frequency_and_more'),
        ('students', '0003_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_new_admission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='transport_fee_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_students', to='fees.feehead'),
        ),
    ]
