# Generated by Django 6.0.1 on 2026-01-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_is_new_admission_student_transport_fee_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('TC', 'TC')], default='Active', max_length=10),
        ),
    ]
