# Generated by Django 6.0.1 on 2026-01-20 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_feetransaction_fee_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='feehead',
            name='session',
            field=models.CharField(default=1999, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feehead',
            name='name',
            field=models.CharField(help_text='e.g. Tuition Fee, Transport Fee', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='feehead',
            unique_together={('name', 'session')},
        ),
        migrations.CreateModel(
            name='FeeAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('Nursery', 'Nursery'), ('KG1', 'KG1'), ('KG2', 'KG2'), ('Class 1', 'Class 1'), ('Class 2', 'Class 2'), ('Class 12', 'Class 12')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='fees.feehead')),
            ],
            options={
                'unique_together': {('fee_head', 'class_name')},
            },
        ),
    ]
