# Generated by Django 6.0.1 on 2026-01-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_alter_feeamount_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feehead',
            name='due_day',
            field=models.IntegerField(default=10, help_text='Day of month for due date (1-31). For quarterly/yearly, first installment day.'),
        ),
        migrations.AddField(
            model_name='feehead',
            name='due_months',
            field=models.CharField(blank=True, help_text="Comma-separated months (1-12). E.g., '4,7,10,1' for quarterly", max_length=50),
        ),
        migrations.AddField(
            model_name='feehead',
            name='frequency',
            field=models.CharField(choices=[('ONCE', 'One Time'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', help_text='How often this fee is collected', max_length=20),
        ),
        migrations.AddField(
            model_name='feehead',
            name='grace_period_days',
            field=models.IntegerField(default=0, help_text='Days after due date before late fee applies'),
        ),
        migrations.AddField(
            model_name='feehead',
            name='late_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Late fee charged after due date', max_digits=10),
        ),
    ]
