# Generated by Django 6.0.1 on 2026-01-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_feehead_due_day_feehead_due_months_feehead_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feehead',
            name='due_months',
            field=models.CharField(blank=True, help_text="Comma-separated months (1-12) for installments. E.g., '4,7,10,1' for 4 installments", max_length=50),
        ),
        migrations.AlterField(
            model_name='feehead',
            name='frequency',
            field=models.CharField(choices=[('ONCE', 'One Time'), ('INSTALLMENTS', 'Installments')], default='MONTHLY', help_text='How often this fee is collected', max_length=20),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='frequency',
            field=models.CharField(choices=[('INSTALLMENTS', 'Installments'), ('ONE_TIME', 'One Time')], default='INSTALLMENTS', max_length=20),
        ),
    ]
