# Generated by Django 6.0.1 on 2026-01-22 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_alter_feehead_due_months_alter_feehead_frequency_and_more'),
        ('students', '0004_student_is_new_admission_student_transport_fee_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='feehead',
            name='is_transport_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='month',
            field=models.IntegerField(default=1, help_text='Month number (1-12)'),
        ),
        migrations.AlterUniqueTogether(
            name='studentfee',
            unique_together={('student', 'fee_head', 'month')},
        ),
        migrations.AlterField(
            model_name='feeamount',
            name='class_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feetransaction',
            name='fee_head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.feehead'),
        ),
        migrations.AlterField(
            model_name='feetransaction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.RemoveField(
            model_name='studentfee',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='studentfee',
            name='paid_date',
        ),
    ]
