# Generated by Django 6.0.1 on 2026-01-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_alter_studentfee_unique_together_and_more'),
        ('students', '0006_student_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='feehead',
            name='installment_count',
            field=models.IntegerField(default=1, help_text='Number of installments'),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='installment_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='installment_number',
            field=models.IntegerField(default=1, help_text='Installment number (1, 2, 3...)'),
        ),
        migrations.AlterUniqueTogether(
            name='studentfee',
            unique_together={('student', 'fee_head', 'installment_number')},
        ),
        migrations.AlterField(
            model_name='feehead',
            name='frequency',
            field=models.CharField(choices=[('ONCE', 'One Time'), ('INSTALLMENTS', 'Installments')], default='INSTALLMENTS', help_text='How often this fee is collected', max_length=20),
        ),
        migrations.RemoveField(
            model_name='studentfee',
            name='month',
        ),
    ]
