# Generated by Django 6.0.1 on 2026-01-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0008_alter_studentfee_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalFeeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=10, unique=True)),
                ('installment_count', models.IntegerField(default=1)),
                ('due_months', models.CharField(help_text='Comma-separated months (1-12)', max_length=100)),
                ('due_day', models.IntegerField(default=10)),
            ],
        ),
    ]
