# Generated by Django 6.0.1 on 2026-01-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0009_globalfeesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetransaction',
            name='receipt_id',
            field=models.CharField(blank=True, help_text='Unique ID to group multiple fee head payments in one go', max_length=50, null=True),
        ),
    ]
