# Generated by Django 6.0.1 on 2026-01-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0011_remove_feetransaction_receipt_id_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalfeesetting',
            name='late_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='globalfeesetting',
            name='late_fee_frequency',
            field=models.CharField(choices=[('ONCE', 'Once'), ('PER_DAY', 'Per Day')], default='ONCE', help_text='Apply once or daily after due date', max_length=20),
        ),
        migrations.AddField(
            model_name='globalfeesetting',
            name='late_fee_start_day',
            field=models.IntegerField(default=15, help_text='Day of month after which late fee is applied'),
        ),
    ]
