# Generated by Django 6.0.1 on 2026-01-30 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0012_globalfeesetting_late_fee_amount_and_more'),
        ('students', '0006_student_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ref_number', models.CharField(blank=True, max_length=100, null=True)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_matches', to='fees.feetransaction')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeeEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(help_text='Academic session (e.g., 2026-27)', max_length=10)),
                ('installment_number', models.IntegerField(help_text='Installment number (1, 2, 3, ...)')),
                ('is_enrolled', models.BooleanField(default=True, help_text='True = enrolled, False = opted out')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='fees.feehead')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_enrollments', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'session'], name='fees_studen_student_03f865_idx'), models.Index(fields=['fee_head', 'session'], name='fees_studen_fee_hea_a10b27_idx')],
                'unique_together': {('student', 'fee_head', 'session', 'installment_number')},
            },
        ),
    ]
