# Generated by Django 6.0.1 on 2026-01-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0013_bankstatemententry_studentfeeenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('ONLINE', 'Online')], default='CASH', max_length=10),
        ),
    ]
