# Generated by Django 6.0.1 on 2026-02-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0014_receipt_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatemententry',
            name='reconciliation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
